[package]
<<<<<<< HEAD
name = "tests"
=======
name = "render3D"
>>>>>>> ccbc06b (Finished 3d base + fixed 2d draw)
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.20"